import { ImageResponse } from "next/og";

/**
 * Shared OpenGraph image template.
 *
 * Each /app/.../opengraph-image.tsx file is a one-line shim that calls
 * renderOgImage({ eyebrow, title, emphasis? }). Next.js generates each PNG
 * once at build time and serves it as a static asset; no runtime cost.
 *
 * Fonts are fetched from the @fontsource jsDelivr mirror at build time.
 * jsDelivr is a stable CDN backed by GitHub; the URLs are pinned to the
 * package version we depend on transitively (Fraunces).
 *
 * The image is intentionally on-brand: paper background, oxblood rule,
 * serif headline. It is generated by Satori (via next/og), which only
 * supports a subset of CSS — keep changes flex-only, no grid, no
 * background images, no shadows beyond simple box-shadows.
 */

export const OG_SIZE = { width: 1200, height: 630 } as const;
export const OG_CONTENT_TYPE = "image/png";

interface OgProps {
  /** Top eyebrow line, will be uppercased and tracked. */
  eyebrow: string;
  /** Headline. */
  title: string;
  /**
   * Optional substring of `title` to render in italic oxblood, matching the
   * page-level emphasis style. If absent or not found in `title`, the
   * headline renders in a single ink color.
   */
  emphasis?: string;
}

// jsDelivr mirror of @fontsource Fraunces — version-pinned for stability.
const FRAUNCES_REGULAR =
  "https://cdn.jsdelivr.net/npm/@fontsource/fraunces@5.0.21/files/fraunces-latin-400-normal.woff";
const FRAUNCES_ITALIC =
  "https://cdn.jsdelivr.net/npm/@fontsource/fraunces@5.0.21/files/fraunces-latin-400-italic.woff";

async function loadFont(url: string): Promise<ArrayBuffer> {
  const res = await fetch(url);
  if (!res.ok) {
    throw new Error(`Failed to load OG font ${url}: HTTP ${res.status}`);
  }
  return res.arrayBuffer();
}

export async function renderOgImage({
  eyebrow,
  title,
  emphasis,
}: OgProps): Promise<ImageResponse> {
  const [fraunces, fraunces_italic] = await Promise.all([
    loadFont(FRAUNCES_REGULAR),
    loadFont(FRAUNCES_ITALIC),
  ]);

  // Split the title around `emphasis` so we can italic-color just that span.
  // If emphasis isn't a substring, the whole title goes in one span.
  // Punctuation immediately after the emphasis word is folded into the
  // emphasis span so flex-wrap can't push a lone comma/period onto its own
  // line (Satori flex items don't break internally).
  const parts: Array<{ text: string; em: boolean }> = [];
  if (emphasis && title.includes(emphasis)) {
    const idx = title.indexOf(emphasis);
    if (idx > 0) parts.push({ text: title.slice(0, idx), em: false });
    let em = emphasis;
    let tail = title.slice(idx + emphasis.length);
    // Fold immediately-following punctuation into the emphasis span so a
    // lonely "," can't end up on its own line under flex-wrap.
    const punctMatch = tail.match(/^[,.;:!?]+/);
    if (punctMatch) {
      em += punctMatch[0];
      tail = tail.slice(punctMatch[0].length);
    }
    // Normalize the boundary: strip leading whitespace from tail and append a
    // single trailing space to em. With whiteSpace:"pre", this means the line
    // break (if any) lands cleanly between em and tail without leaving a
    // visible indent on the wrapped line.
    if (tail.length > 0) {
      tail = tail.replace(/^\s+/, "");
      if (!em.endsWith(" ")) em += " ";
    }
    parts.push({ text: em, em: true });
    if (tail) parts.push({ text: tail, em: false });
  } else {
    parts.push({ text: title, em: false });
  }

  return new ImageResponse(
    (
      <div
        style={{
          width: 1200,
          height: 630,
          background: "#f3eee4",
          display: "flex",
          flexDirection: "column",
          padding: "96px 100px",
          color: "#1a1a24",
          position: "relative",
          fontFamily: "Fraunces",
        }}
      >
        {/* Top oxblood rule */}
        <div
          style={{
            position: "absolute",
            top: 0,
            left: 0,
            right: 0,
            height: 8,
            background: "#6e1f1f",
            display: "flex",
          }}
        />

        {/* Eyebrow — tracked uppercase, ochre */}
        <div
          style={{
            fontSize: 24,
            letterSpacing: 6,
            textTransform: "uppercase",
            color: "#7a5215",
            display: "flex",
            fontWeight: 400,
          }}
        >
          {eyebrow}
        </div>

        {/* Headline. Each part is a sibling flex item; flex-wrap breaks at
            item boundaries only. To prevent unwanted breaks (e.g. punctuation
            after the emphasis word jumping to its own line), the surrounding
            text spans carry their own adjoining spaces and we use zero margin
            between siblings. */}
        <div
          style={{
            marginTop: 52,
            fontSize: 80,
            lineHeight: 1.06,
            letterSpacing: -2,
            display: "flex",
            flexWrap: "wrap",
            fontWeight: 400,
            maxWidth: 1000,
          }}
        >
          {parts.map((p, i) => (
            <span
              key={i}
              style={{
                fontStyle: p.em ? "italic" : "normal",
                color: p.em ? "#6e1f1f" : "#1a1a24",
                whiteSpace: "pre",
              }}
            >
              {p.text}
            </span>
          ))}
        </div>

        {/* Bottom strip — brand + URL */}
        <div
          style={{
            marginTop: "auto",
            paddingTop: 32,
            borderTop: "1px solid #c9bfa5",
            display: "flex",
            justifyContent: "space-between",
            fontSize: 20,
            letterSpacing: 4,
            textTransform: "uppercase",
            color: "#5a5a68",
          }}
        >
          <span>The Authority Arc</span>
          <span>systemslibrarian.dev</span>
        </div>
      </div>
    ),
    {
      ...OG_SIZE,
      fonts: [
        {
          name: "Fraunces",
          data: fraunces,
          style: "normal",
          weight: 400,
        },
        {
          name: "Fraunces",
          data: fraunces_italic,
          style: "italic",
          weight: 400,
        },
      ],
    }
  );
}
